#!/bin/sh
#
# パラメータで渡されたファイルを.backupに退避後、vimで開く

usage() {
    echo "Invalid option!"
    echo "Usage: $0 file"
}

if [ $# != 1 ]; then
    usage
    exit 1
fi
if [ -f $1 ]; then
    if [ ! -f $1.backup ]; then
        mv $1 $1.backup
        cp $1.backup $1
    fi
    vim $1
else
    usage
    exit 1
fi
exit 0
